//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aykutproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        public int Dersid { get; set; }
        public string DersAd { get; set; }
        public string Dersicerik { get; set; }
        public string DersDurum { get; set; }
        public int dKatid { get; set; }
        public int dUyeid { get; set; }
        public System.DateTime dBaslamaTarih { get; set; }
        public System.DateTime dBitirmeTarih { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
